### PR TITLE
Fabric 1.19

### PR DESCRIPTION
**Pull request by DaFuqs**
Ported it for a friend.
No idea if you want to manage a fabric port, but I'll gladly offer a fully working version and will do 1.18.2 and 1.19.3, too.

### CODE REVIEW

**Comment by DaFuqs** [comment]
Fabric 1.18 & 1.19.3 are done, too

**Comment by DaFuqs** [comment]
If you don't want to maintain fabric ports, I will happily offer doing so - with your permission, of course.

**Comment by hibiii** [comment]
no port works, error on entrypoint stage main, on 1.18.x and 1.19.x: `Caused by: java.lang.IllegalStateException: Registry is already frozen`, on 1.19.3 `Caused by: java.lang.IllegalStateException: This registry can't create intrusive holders`.

java: eclipse adoptium 17.0.4 amd64
other mods: none, no dependency reported by loader

**Comment by hibiii** [comment]
closing as not planned

**Pull request closed without merging**
