### PR TITLE
port to forge 1.19.2

### PR DESCRIPTION
**Pull request by justliliandev**
I suggest you to make a seperate branch for the forge version of this mod.
Also I gotta say: the blahaj model is really cute

### CODE REVIEW

**Comment by hibiii** [comment]
i want a forge port to be a single source solution, i don't want to rewrite literally the entire mod because i changed mod loaders, because maintaining multiple branches for different loaders gets increasingly more difficult over time as the architecture, mappings, apis, and lower level components for each loader change over time, which would make my life slightly less enjoyable.

perhaps you should host these diffs in a repository, like a set of patches to apply, kind of like the idiots at s\*ckless do it.

also be careful with mojmapped code, seeing them could legally put people in trouble.

major edit: edited to better reflect how i actually feel about a forge port.

**Comment by hibiii** [comment]
@agnor99 look, i thought over this and i'm sorry i lashed out at you, i'm in a particularly vulnerable and stressful moment in my life, very rarely do i get any moment of calm, i have long term plans in jeopardy, people i trust and who trust me randomly decide to confront me in a hurtful way, even inside my own house, that combined with the publicity i was not expecting - that's why i can't dedicate much time to modding, i want to but i feel unsafe to do so. anyway, i realize i've been way too harsh, and i shouldn't have exchanged expletives and shouldn't have immediately discarded your idea. the facts you immediately created a pull without even creating an issue, and the pull changed pretty much every single file made me go mad and that was the tipping point for me. i understand now that you were just trying to help and i was hotheaded. for that, i'm sorry.

anyway, github is not the place for cryey talk, i'll keep this pull closed because i think doubling work with individual loader ports is a very bad idea over time, but i'll look into single-source multi-loader solutions.

**Comment by justliliandev** [comment]
that wasn't my purpose, I'm sorry for that.

Back to topic: I don't know how you get the impression that seeing the mappings is a problem, maybe you remember the old license (pre August 2020 iirc)

This is the license Header for the mappings as of now:
> \# (c) 2020 Microsoft Corporation. These mappings are provided "as-is" and you bear the risk of using them. You may copy and use the mappings for development purposes, but you may not redistribute the mappings complete and unmodified. Microsoft makes no warranties, express or implied, with respect to the mappings provided here.  Use and modification of this document or the source code (in any form) of Minecraft: Java Edition is governed by the Minecraft End User License Agreement available at https://account.mojang.com/documents/minecraft_eula.

> You may copy and use the mappings for development purposes

So for gh codehosting, references in development docs etc these should be useable. The next part is what restricts the usage:
> [...] you may not redistribute the mappings complete and unmodified.

As this mod doesn't touch all classes, this mod doesn't redistribute the mappings complete and even if it would, this mod would distrubte them modified (added stuff because because of the code around them)

Also I would be willing to help you with an architectury solution if you are willing to accept that.
(I kinda doubt that MultiLoader Plugin is the solution for this kind of mod from my experience, but if you want to use that, I would be willing to help you with that as well)

**Comment by hibiii** [comment]
> (c) 2020 Microsoft Corporation.

stopped reading right there /j

i've been trying to warp my head around forge and i have even more questions than i started with, but i'd be glad if you could do the forge part of an architectury port

i'll play around and see if i can convert the mod to arc8y mod without much issue

**Pull request closed without merging**
